version: 2.1

jobs:
  js-test:
    machine: true
    working_directory: ~/repo

    steps:
      - checkout
      - run: npx envinfo
      - run: docker-compose up -d

workflows:
  test-ci:
    jobs:
      - js-test
