version: 2.1

jobs:
  js-test:
    machine: true
    working_directory: ~/repo

    steps:
      - checkout
      - run: npx envinfo

  arm64-build:
    docker:
      - image: gengjiawen/v8-build
    working_directory: ~/repo
    steps:
      - checkout
      - run: npx envinfo
      - run:
          command: |
            cd ~/v8
            git checkout origin/lkgr
            node ~/repo/v8gen.js
            time ninja -C out/arm64.release/


workflows:
  test-ci:
    jobs:
      - js-test
      - arm64-build
