version: 2.1

jobs:
  js-test:
    machine: true
    working_directory: ~/repo

    steps:
      - checkout
      - run: npx envinfo
      - run: docker-compose up -d
  arm64-build:
    docker:
      - image: gengjiawen/v8-build
    working_directory: ~/repo

    steps:
      - checkout
      - run: npx envinfo
      - run:
          command: |
            cd ~/v8
            node ~/repo/v8gen.js


workflows:
  test-ci:
    jobs:
      - js-test
      - arm64-build
