name: CI

on: [push, pull_request]

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    container: gengjiawen/v8-build:arm64
    steps:
      - uses: actions/checkout@v2
      - name: Build arm64
        run: |
            cd /root/v8
            git checkout origin/lkgr
            node $GITHUB_WORKSPACE/v8gen.js
            time ninja -C out/arm64.release/