name: CI

on: [push, pull_request]

jobs:
  build-linux-arm64:
    runs-on: ubuntu-latest
    container: gengjiawen/v8-build:arm64
    steps:
      - uses: actions/checkout@v2
      - name: Build arm64
        run: |
          cd /root/v8
          git checkout origin/lkgr
          node $GITHUB_WORKSPACE/v8gen.js
          time ninja -C out/arm64.release/
      - uses: actions/upload-artifact@v2
        with:
          name: v8-arm64
          path: /root/v8/out/arm64.release/
