name: CI

on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest
    container: gengjiawen/v8-build
    steps:
      - uses: actions/checkout@v2
      - name: Build arm64
        run: |
            cd ~/v8
            git checkout origin/lkgr
            node ~/repo/v8gen.js
            time ninja -C out/arm64.release/